apiVersion: 2018-06-01
location: eastus
name: myResourceGroup
properties:
  containers:
  - name: backend
    properties:
      image: backend:v1
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 80
      - port: 8080
#  - name: aci-tutorial-sidecar
#    properties:
#      image: microsoft/aci-tutorial-sidecar
#      resources:
#        requests:
#          cpu: 1
#          memoryInGb: 1.5
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: '80'
    - protocol: tcp
      port: '8080'
tags: null
type: Microsoft.ContainerInstance/containerGroups
