version: "3"
services:
    calderasBackend:
        image: backend
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure        
        ports:
            - "80:8080"


#    calderasFrontend:
#        image: calderasFrontend
#        deploy:
#            replicas: 1
#            restart_policy:
#                condition: on-failure
#        ports:
#            - "80:4200"


